### ISSUE TITLE
What to download - what to start

### ISSUE THREAD

**Issue by nickbe** [ggellene/qiki#6]
hey there.

I just downloaded the master. But the mentioned qiki.html seems not to be there.
At least not something we can actuall use.
The only qiki.html is inside the app folder but all I can see is a save / load button.
Nothing happens.

**Comment by ggellene** [comment]
Yes, this isn't really functional. I stopped working on it a while ago because it was honestly less work to host a regular wiki online somewhere.

The one I'm using is https://github.com/jgm/gitit, fwiw.
